stages:
  - build



build-pi:
  stage: build
  tags:
    - arm
    - raspberrypi
    - native
  script:
    - mkdir arm
    - cd arm
    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ENCRYPT=ON ..
    - make
    - rm CMakeCache.txt
    - rm Makefile
    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_DECRYPT=ON ..
    - make
  artifacts:
    paths:
      - arm/crye
      - arm/cryd

build-pi4:
  stage: build
  tags:
    - arm
    - pi4
    - native
  script:
    - mkdir arm
    - cd arm
    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ENCRYPT=ON ..
    - make
    - rm CMakeCache.txt
    - rm Makefile
    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_DECRYPT=ON ..
    - make
  artifacts:
    paths:
      - arm/crye
      - arm/cryd
    


build-gcc:
  image: gcc
  stage: build
  tags:
    - linux
    - docker
  before_script:
    - apt update
    - apt -y install make cmake
    - apt -y install libboost-system1.67-dev libboost-date-time1.67-dev
    - apt -y install libboost-filesystem1.67-dev libboost-program-options1.67-dev
    - apt -y install libgcrypt20-dev
  script:
    - mkdir nix
    - cd nix
    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ENCRYPT=ON ..
    - make
    - rm CMakeCache.txt
    - rm Makefile
    - cmake -DCMAKE_BUILD_TYPE=Relase -DBUILD_DECRYPT=ON ..
    - make
  artifacts:
    paths:
      - nix/crye
      - nix/cryd
      #- mybinary
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"


build-win:
  stage: build
  tags:
    - win10
    - vs2019
    - native
  before_script:
    - cmd /c "echo mkdir win10 > mybuild.bat"
    - cmd /c "echo copy e:\sdk\shared\bin\libgcrypt-20.dll win10\ >> mybuild.bat"
    - cmd /c "echo copy e:\sdk\shared\bin\libgpg-error6-0.dll win10\ >> mybuild.bat"
    - cmd /c "echo cd win10 >> mybuild.bat"
    - cmd /c "echo SET SDK_ROOT=e:\sdk\shared>> mybuild.bat"
    - cmd /c "echo SET PATH=%SDK_ROOT%\bin;%PATH%>> mybuild.bat"
    - cmd /c "echo SET include=%SDK_ROOT%\include;%include%>> mybuild.bat"
    - cmd /c "echo SET lib=%SDK_ROOT%\lib;%lib%>> mybuild.bat"
    - cmd /c "echo call vcvarsall x64 >> mybuild.bat"
    - cmd /c 'echo cmake -G "NMake Makefiles" -DBUILD_ENCRYPT=ON -DCMAKE_BUILD_TYPE=Release .. >> mybuild.bat'
    - cmd /c "echo nmake >> mybuild.bat"
    - cmd /c "echo del CMakeCache.txt Makefile >> mybuild.bat"
    - cmd /c 'echo cmake -G "NMake Makefiles" -DBUILD_DECRYPT=ON -DCMAKE_BUILD_TYPE=Release .. >> mybuild.bat'
    - cmd /c "echo nmake >> mybuild.bat"
    
  script:
    - cmd /c "mybuild.bat"
  artifacts:
    paths:
      - win10/crye.exe
      - win10/cryd.exe
      - win10/libgcrypt-20.dll
      - win10/libgpg-error6-0.dll
