#ifndef CRY_VERSION_H
#define CRY_VERSION_H

#define CRY_VERSION_MAJOR 0)
#define CRY_VERSION_MINOR 1)
#define CRY_VERSION_BUILD 10)
#define CRY_VERSION_STRING "0.1.10")

#endif //CRY_VERSION_H
