#ifndef CRY_VERSION_H
#define CRY_VERSION_H

#define CRY_VERSION_MAJOR 0)
#define CRY_VERSION_MINOR 2)
#define CRY_VERSION_BUILD 17)
#define CRY_VERSION_STRING "0.2.17")

#endif //CRY_VERSION_H
